apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pal-tracker
spec:
  rules:
    - host: development.tracker.13.57.232.48.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: pal-tracker
              servicePort: 8080