apiVersion: apps/v1
kind: Deployment
metadata:
  name: pal-tracker
  labels:
    app: pal-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pal-tracker
      name: pal-tracker-pod
  template:
    # Pod definition starts here
    metadata:
      labels:
        app: pal-tracker
        name: pal-tracker-pod
    spec:
      containers:
        - name: pal-tracker-container
          image: kabhay1984/pal-tracker:v3
          readinessProbe:
             httpGet:
               path: /actuator/health/readiness
               port: 8080
          livenessProbe:
             httpGet:
               path: /actuator/health/liveness
               port: 8080
             initialDelaySeconds: 150
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sleep", "10" ]
          env:
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "info,health,palTrackerFailure"
            - name: MANAGEMENT_ENDPOINT_HEALTH_GROUP_READINESS_INCLUDE
              value: "backingService"
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: pal-tracker
                  key: welcome.message
